/*
# Seed the existing teacher Directory records

1. Data
- Inserts the ten teacher records from src/data.ts without rewriting names, descriptions, coordinates, or attributes.
- Preserves each original identifier as legacy_id.
2. Safety
- Uses legacy_id conflict updates so the seed is repeatable.
- Every record remains published because these are the existing public Directory records.
*/
INSERT INTO public.teachers (legacy_id,name,area,lat,lng,description,payload,is_published) VALUES ('t1','佐藤美咲｜呼吸とやさしいヨガ','渋谷',35.6595,139.7005,'初心者に寄り添いながら、呼吸法とリラックスを丁寧に伝える先生です。少人数制のやわらかな進行で、英語対応の案内も交えつつ安心して始められる雰囲気を大切にしています。','{"id":"t1","name":"佐藤美咲｜呼吸とやさしいヨガ","type":"teacher","area":"渋谷","lat":35.6595,"lng":139.7005,"description":"初心者に寄り添いながら、呼吸法とリラックスを丁寧に伝える先生です。少人数制のやわらかな進行で、英語対応の案内も交えつつ安心して始められる雰囲気を大切にしています。","targetLevels":["初心者","中級者","産後"],"specialties":["リラックスヨガ","呼吸法","睡眠改善","メンタルケア"],"formats":["個別レッスン","グループレッスン","オンライン"],"certifications":["RYT200","メディテーション指導"],"foreignSupportStatus":"対応可能","languages":["日本語","英語"],"languageLevel":"レッスン対応可能","proYogaStatus":"プロYoga検定取得"}'::jsonb,true) ON CONFLICT (legacy_id) DO UPDATE SET name=EXCLUDED.name,area=EXCLUDED.area,lat=EXCLUDED.lat,lng=EXCLUDED.lng,description=EXCLUDED.description,payload=EXCLUDED.payload,is_published=true;
INSERT INTO public.teachers (legacy_id,name,area,lat,lng,description,payload,is_published) VALUES ('t2','KEN MORI｜姿勢改善ヨガ','銀座',35.6717,139.765,'姿勢改善や肩こり改善に強く、体の使い方をわかりやすく伝えてくれる先生です。はじめての方にも無理のない言葉で寄り添い、実感につながるレッスンを心がけています。','{"id":"t2","name":"KEN MORI｜姿勢改善ヨガ","type":"teacher","area":"銀座","lat":35.6717,"lng":139.765,"description":"姿勢改善や肩こり改善に強く、体の使い方をわかりやすく伝えてくれる先生です。はじめての方にも無理のない言葉で寄り添い、実感につながるレッスンを心がけています。","targetLevels":["初心者","中級者","企業向け"],"specialties":["姿勢改善","肩こり改善","腰痛改善","ハタヨガ"],"formats":["個別レッスン","企業研修","出張"],"certifications":["理学療法連携講座","解剖学研修"],"foreignSupportStatus":"一部対応可能","languages":["日本語","英語"],"languageLevel":"日常会話レベル","proYogaStatus":"取得予定"}'::jsonb,true) ON CONFLICT (legacy_id) DO UPDATE SET name=EXCLUDED.name,area=EXCLUDED.area,lat=EXCLUDED.lat,lng=EXCLUDED.lng,description=EXCLUDED.description,payload=EXCLUDED.payload,is_published=true;
INSERT INTO public.teachers (legacy_id,name,area,lat,lng,description,payload,is_published) VALUES ('t3','Luna Zhang｜国際ウェルネスヨガ','新宿',35.6896,139.692,'英語対応・中国語対応ができ、初心者に寄り添いながら呼吸法とマインドフルネスを丁寧に深めてくれる先生です。国際的な背景を活かした落ち着いた指導が魅力です。','{"id":"t3","name":"Luna Zhang｜国際ウェルネスヨガ","type":"teacher","area":"新宿","lat":35.6896,"lng":139.692,"description":"英語対応・中国語対応ができ、初心者に寄り添いながら呼吸法とマインドフルネスを丁寧に深めてくれる先生です。国際的な背景を活かした落ち着いた指導が魅力です。","targetLevels":["初心者","中級者","インストラクター向け"],"specialties":["瞑想","呼吸法","メンタルケア","ヨガ哲学"],"formats":["グループレッスン","オンライン","イベント登壇"],"certifications":["国際瞑想ファシリテーター"],"foreignSupportStatus":"対応可能","languages":["日本語","中国語","英語"],"languageLevel":"専門指導可能","proYogaStatus":"プロYoga検定取得"}'::jsonb,true) ON CONFLICT (legacy_id) DO UPDATE SET name=EXCLUDED.name,area=EXCLUDED.area,lat=EXCLUDED.lat,lng=EXCLUDED.lng,description=EXCLUDED.description,payload=EXCLUDED.payload,is_published=true;
INSERT INTO public.teachers (legacy_id,name,area,lat,lng,description,payload,is_published) VALUES ('t4','Chiara｜リラックスフローヨガ','表参道',35.665,139.712,'英語対応と外国人対応に強く、やわらかな人柄で初参加でも緊張しにくい先生です。少人数クラスを中心に、流れるような動きと国際交流の楽しさを自然に届けています。','{"id":"t4","name":"Chiara｜リラックスフローヨガ","type":"teacher","area":"表参道","lat":35.665,"lng":139.712,"description":"英語対応と外国人対応に強く、やわらかな人柄で初参加でも緊張しにくい先生です。少人数クラスを中心に、流れるような動きと国際交流の楽しさを自然に届けています。","targetLevels":["初心者","中級者","上級者"],"specialties":["ヴィンヤサ","瞑想","国際交流","呼吸法"],"formats":["グループレッスン","イベント登壇","オンライン"],"certifications":["European Yoga Certification"],"foreignSupportStatus":"対応可能","languages":["日本語","英語","イタリア語"],"languageLevel":"専門指導可能","proYogaStatus":"取得予定"}'::jsonb,true) ON CONFLICT (legacy_id) DO UPDATE SET name=EXCLUDED.name,area=EXCLUDED.area,lat=EXCLUDED.lat,lng=EXCLUDED.lng,description=EXCLUDED.description,payload=EXCLUDED.payload,is_published=true;
INSERT INTO public.teachers (legacy_id,name,area,lat,lng,description,payload,is_published) VALUES ('t5','佐伯遥｜やさしいケアヨガ','世田谷',35.6464,139.6532,'初心者や産後ケアの方にも穏やかに寄り添う、地域密着型の先生です。無理なく続けられるペースを大切にしながら、安心感のあるレッスンづくりを行っています。','{"id":"t5","name":"佐伯遥｜やさしいケアヨガ","type":"teacher","area":"世田谷","lat":35.6464,"lng":139.6532,"description":"初心者や産後ケアの方にも穏やかに寄り添う、地域密着型の先生です。無理なく続けられるペースを大切にしながら、安心感のあるレッスンづくりを行っています。","targetLevels":["初心者","シニア","産後"],"specialties":["リラックスヨガ","産後ケア","腰痛改善","睡眠改善"],"formats":["個別レッスン","グループレッスン","出張"],"certifications":["産後指導認定"],"foreignSupportStatus":"対応不可","languages":["日本語"],"languageLevel":"日常会話レベル","proYogaStatus":"未取得"}'::jsonb,true) ON CONFLICT (legacy_id) DO UPDATE SET name=EXCLUDED.name,area=EXCLUDED.area,lat=EXCLUDED.lat,lng=EXCLUDED.lng,description=EXCLUDED.description,payload=EXCLUDED.payload,is_published=true;
INSERT INTO public.teachers (legacy_id,name,area,lat,lng,description,payload,is_published) VALUES ('t6','藤田尚子｜資格サポートヨガ','青山',35.6659,139.7123,'資格サポートとプロYoga対応に強く、哲学と実技の両面を丁寧に導く先生です。専門性がありながらも説明は親身で、学び直しや資格取得を目指す方に心強い存在です。','{"id":"t6","name":"藤田尚子｜資格サポートヨガ","type":"teacher","area":"青山","lat":35.6659,"lng":139.7123,"description":"資格サポートとプロYoga対応に強く、哲学と実技の両面を丁寧に導く先生です。専門性がありながらも説明は親身で、学び直しや資格取得を目指す方に心強い存在です。","targetLevels":["中級者","上級者","インストラクター向け"],"specialties":["資格対策","ヨガ哲学","呼吸法","姿勢改善"],"formats":["養成講座講師","スクール講師","オンライン"],"certifications":["RYT500","哲学講師認定"],"foreignSupportStatus":"一部対応可能","languages":["日本語","英語"],"languageLevel":"レッスン対応可能","proYogaStatus":"プロYoga検定取得"}'::jsonb,true) ON CONFLICT (legacy_id) DO UPDATE SET name=EXCLUDED.name,area=EXCLUDED.area,lat=EXCLUDED.lat,lng=EXCLUDED.lng,description=EXCLUDED.description,payload=EXCLUDED.payload,is_published=true;
INSERT INTO public.teachers (legacy_id,name,area,lat,lng,description,payload,is_published) VALUES ('t7','加藤えみ｜アクティブビギナーヨガ','恵比寿',35.6467,139.7101,'初心者に寄り添いながら、姿勢改善や運動不足解消へ前向きに導いてくれる先生です。明るい人柄で参加しやすく、続けたくなるリズム感のあるクラスが特長です。','{"id":"t7","name":"加藤えみ｜アクティブビギナーヨガ","type":"teacher","area":"恵比寿","lat":35.6467,"lng":139.7101,"description":"初心者に寄り添いながら、姿勢改善や運動不足解消へ前向きに導いてくれる先生です。明るい人柄で参加しやすく、続けたくなるリズム感のあるクラスが特長です。","targetLevels":["初心者","中級者","男性向け"],"specialties":["パワーヨガ","ダイエット","運動不足解消","ヴィンヤサ"],"formats":["グループレッスン","オンライン","イベント登壇"],"certifications":["フィットネス連携修了"],"foreignSupportStatus":"一部対応可能","languages":["日本語","英語"],"languageLevel":"レッスン対応可能","proYogaStatus":"未取得"}'::jsonb,true) ON CONFLICT (legacy_id) DO UPDATE SET name=EXCLUDED.name,area=EXCLUDED.area,lat=EXCLUDED.lat,lng=EXCLUDED.lng,description=EXCLUDED.description,payload=EXCLUDED.payload,is_published=true;
INSERT INTO public.teachers (legacy_id,name,area,lat,lng,description,payload,is_published) VALUES ('t8','西村太郎｜ビジネスヨガサポート','品川',35.6285,139.7387,'肩こり改善やリラックスをテーマに、忙しい方にも続けやすい提案をしてくれる先生です。少人数制の個別対応を得意とし、英語対応の案内も交えながら丁寧に伴走します。','{"id":"t8","name":"西村太郎｜ビジネスヨガサポート","type":"teacher","area":"品川","lat":35.6285,"lng":139.7387,"description":"肩こり改善やリラックスをテーマに、忙しい方にも続けやすい提案をしてくれる先生です。少人数制の個別対応を得意とし、英語対応の案内も交えながら丁寧に伴走します。","targetLevels":["初心者","企業向け","男性向け"],"specialties":["肩こり改善","睡眠改善","メンタルケア"],"formats":["個別レッスン","企業研修","オンライン"],"certifications":["企業ウェルネス講師"],"foreignSupportStatus":"一部対応可能","languages":["日本語","英語"],"languageLevel":"日常会話レベル","proYogaStatus":"取得予定"}'::jsonb,true) ON CONFLICT (legacy_id) DO UPDATE SET name=EXCLUDED.name,area=EXCLUDED.area,lat=EXCLUDED.lat,lng=EXCLUDED.lng,description=EXCLUDED.description,payload=EXCLUDED.payload,is_published=true;
INSERT INTO public.teachers (legacy_id,name,area,lat,lng,description,payload,is_published) VALUES ('t9','Mei Lin｜少人数グローバルヨガ','上野',35.7138,139.7773,'英語対応・外国人対応に加え、少人数で一人ひとりを見ながら進めるのが得意な先生です。初心者にも寄り添い、呼吸法や姿勢改善を無理なく身につけられるよう支えます。','{"id":"t9","name":"Mei Lin｜少人数グローバルヨガ","type":"teacher","area":"上野","lat":35.7138,"lng":139.7773,"description":"英語対応・外国人対応に加え、少人数で一人ひとりを見ながら進めるのが得意な先生です。初心者にも寄り添い、呼吸法や姿勢改善を無理なく身につけられるよう支えます。","targetLevels":["初心者","中級者","キッズ"],"specialties":["少人数","呼吸法","肩こり改善","瞑想"],"formats":["グループレッスン","個別レッスン"],"certifications":["Kids Yoga Trainer"],"foreignSupportStatus":"対応可能","languages":["日本語","中国語","英語"],"languageLevel":"専門指導可能","proYogaStatus":"未取得"}'::jsonb,true) ON CONFLICT (legacy_id) DO UPDATE SET name=EXCLUDED.name,area=EXCLUDED.area,lat=EXCLUDED.lat,lng=EXCLUDED.lng,description=EXCLUDED.description,payload=EXCLUDED.payload,is_published=true;
INSERT INTO public.teachers (legacy_id,name,area,lat,lng,description,payload,is_published) VALUES ('t10','野村彩花｜地域つながるヨガ','吉祥寺',35.7033,139.5796,'地域のつながりを大切にしながら、初心者に寄り添うやさしい先生です。リラックス中心の指導で、仲間と続けたい方にも心地よい空気感をつくっています。','{"id":"t10","name":"野村彩花｜地域つながるヨガ","type":"teacher","area":"吉祥寺","lat":35.7033,"lng":139.5796,"description":"地域のつながりを大切にしながら、初心者に寄り添うやさしい先生です。リラックス中心の指導で、仲間と続けたい方にも心地よい空気感をつくっています。","targetLevels":["初心者","中級者","シニア"],"specialties":["リラックスヨガ","仲間と続けたい","姿勢改善"],"formats":["グループレッスン","イベント登壇"],"certifications":["地域健康づくり認定"],"foreignSupportStatus":"対応不可","languages":["日本語"],"languageLevel":"日常会話レベル","proYogaStatus":"未取得"}'::jsonb,true) ON CONFLICT (legacy_id) DO UPDATE SET name=EXCLUDED.name,area=EXCLUDED.area,lat=EXCLUDED.lat,lng=EXCLUDED.lng,description=EXCLUDED.description,payload=EXCLUDED.payload,is_published=true;