/*
# Import breath_manager_v5 passages (231 rows)

Source: Boltに渡す_呼吸DB第5版.json
All passages from 17 source documents. content = text_transcribed, section_label = region, page_label = printed_label.
*/

INSERT INTO breath_manager_v5.bm5_passages (passage_id, source_id, chapter, section_label, content, page_label) VALUES ('P01', 'BM-CH01', NULL, '図版2〜3 左上・右上・右中段', '吸った空気は、生命のエネルギーに変わり、すべての細胞を支えています。酸素は、赤血球に乗って全身を巡り、約37兆個の細胞の中にあるミトコンドリアでエネルギー（ATP）に変わります。細胞の中のミトコンドリアが酸素と栄養を使って、エネルギー（ATP）をつくり出します。', '図版2〜3') ON CONFLICT (passage_id) DO NOTHING;
INSERT INTO breath_manager_v5.bm5_passages (passage_id, source_id, chapter, section_label, content, page_label) VALUES ('P02', 'BM-CH01', NULL, 'P4 4段階の見出しと説明', '①換気（Ventilation） 空気を肺へ出し入れする②ガス交換（Gas Exchange） 肺胞で酸素と二酸化炭素を入れ替える③運搬（Transport） 血液で全身に酸素を運ぶ④細胞呼吸（Cellular Respiration） 細胞で酸素を使ってATPをつくる', 'P4') ON CONFLICT (passage_id) DO NOTHING;
INSERT INTO breath_manager_v5.bm5_passages (passage_id, source_id, chapter, section_label, content, page_label) VALUES ('P03', 'BM-CH01', NULL, 'P4 換気・外呼吸・酸素運搬の説明', '横隔膜が下がり肺がふくらむことで空気が入り、肺がしぼむことで空気がが出ます。肺胞でのガス交換を外呼吸、細胞でのガス交換を内呼吸と呼びます。酸素は血液に乗って全身の細胞に運ばれます。', 'P4') ON CONFLICT (passage_id) DO NOTHING;
INSERT INTO breath_manager_v5.bm5_passages (passage_id, source_id, chapter, section_label, content, page_label) VALUES ('P04', 'BM-CH01', NULL, 'P5 上部・右側・下部ATP図', '酸素は糖質や脂質をATPへ変換するために必要な物質です。ATPは細胞のエネルギー通貨です。', 'P5') ON CONFLICT (passage_id) DO NOTHING;
INSERT INTO breath_manager_v5.bm5_passages (passage_id, source_id, chapter, section_label, content, page_label) VALUES ('P05', 'BM-CH01', NULL, 'P6 上部・呼吸調節・pH・ボーア効果', '二酸化炭素（CO₂）は不要な老廃物ではありません。呼吸調節、血液pHの維持、ボーア効果など、生命維持に重要な役割を果たします。', 'P6') ON CONFLICT (passage_id) DO NOTHING;
INSERT INTO breath_manager_v5.bm5_passages (passage_id, source_id, chapter, section_label, content, page_label) VALUES ('P06', 'BM-CH01', NULL, 'P6 左中央・左下', 'CO₂がなければ、呼吸のスイッチが入らず、私たちは呼吸ができなくなります。', 'P6') ON CONFLICT (passage_id) DO NOTHING;
INSERT INTO breath_manager_v5.bm5_passages (passage_id, source_id, chapter, section_label, content, page_label) VALUES ('P07', 'BM-CH01', NULL, 'P7 上部・中央・下部の数値と一般化', '人体は約37兆個の細胞から構成されます。', 'P7') ON CONFLICT (passage_id) DO NOTHING;
INSERT INTO breath_manager_v5.bm5_passages (passage_id, source_id, chapter, section_label, content, page_label) VALUES ('P08', 'BM-CH01', NULL, 'P8 呼吸数セルフチェックと評価表', '安静にして、1分間の呼吸数（呼吸回数）を数えましょう。', 'P8') ON CONFLICT (passage_id) DO NOTHING;
INSERT INTO breath_manager_v5.bm5_passages (passage_id, source_id, chapter, section_label, content, page_label) VALUES ('P09', 'BM-CH01', NULL, 'P8 呼吸タイプ・鼻口・胸郭・横隔膜・肩の観察項目', 'あなたの呼吸の特徴をチェックしましょう。（複数チェック可）', 'P8') ON CONFLICT (passage_id) DO NOTHING;
INSERT INTO breath_manager_v5.bm5_passages (passage_id, source_id, chapter, section_label, content, page_label) VALUES ('P10', 'BM-CH01', NULL, 'P9 中央の関連領域と呼吸カルテ欄', 'ストレス／睡眠／脳・集中力／心臓・血液循環／運動・パフォーマンス／食事・腸内環境／感情・メンタル／ヨガ・自律神経', 'P9') ON CONFLICT (passage_id) DO NOTHING;
INSERT INTO breath_manager_v5.bm5_passages (passage_id, source_id, chapter, section_label, content, page_label) VALUES ('P11', 'BM-CH01', NULL, 'P10 宣言と記録の案内', '私は、今日から自分の呼吸を観察し、理解し、整え、一生付き合っていくことを誓います。', 'P10') ON CONFLICT (passage_id) DO NOTHING;
INSERT INTO breath_manager_v5.bm5_passages (passage_id, source_id, chapter, section_label, content, page_label) VALUES ('P12', 'BM-CH17', NULL, '第17章 導入中央下部', 'プラーナーヤーマは、呼吸に気づき、呼吸を意識的に整えるヨガの実践です。', '第17章') ON CONFLICT (passage_id) DO NOTHING;
INSERT INTO breath_manager_v5.bm5_passages (passage_id, source_id, chapter, section_label, content, page_label) VALUES ('P13', 'BM-CH17', NULL, '17-2 実践 自然呼吸観察', '1 楽な姿勢で座る 2 肩、あご、お腹の力を抜く 3 鼻から自然に吸い、鼻から自然に吐く 4 呼吸を変えようとせず、流れを観察する 5 目安は1〜3分', '17-2') ON CONFLICT (passage_id) DO NOTHING;
INSERT INTO breath_manager_v5.bm5_passages (passage_id, source_id, chapter, section_label, content, page_label) VALUES ('P14', 'BM-CH17', NULL, '17-2 重要ポイント', '初心者は、強い呼吸法から始める必要はありません。まずは、自然な呼吸に気づくことが土台になります。', '17-2') ON CONFLICT (passage_id) DO NOTHING;
INSERT INTO breath_manager_v5.bm5_passages (passage_id, source_id, chapter, section_label, content, page_label) VALUES ('P15', 'BM-CH17', NULL, '17-3 左側 学習テーマ・重要ポイント', 'プラーナとは、ヨガで使われる生命エネルギーを表す考え方です。プラーナーヤーマは、そのプラーナを呼吸を通じて整える実践として扱われます。', '17-3') ON CONFLICT (passage_id) DO NOTHING;
INSERT INTO breath_manager_v5.bm5_passages (passage_id, source_id, chapter, section_label, content, page_label) VALUES ('P16', 'BM-CH17', NULL, '17-3 ナディショーダナ簡易版 実践手順', '目的：左右の鼻を交互に使い、呼吸をゆっくり整える呼吸法です。初心者向けには、息止めを入れずに行います。', '17-3') ON CONFLICT (passage_id) DO NOTHING;
INSERT INTO breath_manager_v5.bm5_passages (passage_id, source_id, chapter, section_label, content, page_label) VALUES ('P17', 'BM-CH17', NULL, '17-3 ナディショーダナ ペースと注意点', '最初は、吸う息と吐く息を同じ長さにします。慣れてきたら、吐く息を少し長くします（吸気：呼気＝1：2へ）。', '17-3') ON CONFLICT (passage_id) DO NOTHING;
INSERT INTO breath_manager_v5.bm5_passages (passage_id, source_id, chapter, section_label, content, page_label) VALUES ('P18', 'BM-CH17', NULL, '17-3 シータリー 実践と対象外', '1 楽な姿勢で座る 2 舌を筒状に丸める 3 その穴から吸い、鼻から吐く 4 目安は1〜3分', '17-3') ON CONFLICT (passage_id) DO NOTHING;
INSERT INTO breath_manager_v5.bm5_passages (passage_id, source_id, chapter, section_label, content, page_label) VALUES ('P19', 'BM-CH17', NULL, '17-3 シートカーリー補足', '舌を筒状に丸められない人もいます。その場合、伝統的にはシートカーリーという冷却系の呼吸法が紹介されることがあります。', '17-3') ON CONFLICT (passage_id) DO NOTHING;
INSERT INTO breath_manager_v5.bm5_passages (passage_id, source_id, chapter, section_label, content, page_label) VALUES ('P20', 'BM-CH17', NULL, '17-4 ブラーマリー簡易版 手順とポイント', '1 楽な姿勢で座る 2 鼻から吸う 3 喉の奥でブーンと音を出しながら吐く 4 目安は1〜3分', '17-4') ON CONFLICT (passage_id) DO NOTHING;
INSERT INTO breath_manager_v5.bm5_passages (passage_id, source_id, chapter, section_label, content, page_label) VALUES ('P21', 'BM-CH17', NULL, '17-4 特徴・教材内での扱い', 'カパラバティは、腹部の収縮を使った強い吐く動きと、受動的な吸う動きを伴う実践です。', '17-4') ON CONFLICT (passage_id) DO NOTHING;
INSERT INTO breath_manager_v5.bm5_passages (passage_id, source_id, chapter, section_label, content, page_label) VALUES ('P22', 'BM-CH17', NULL, '17-4 CYP記載として紹介される数値・禁忌', '初心者：20回程度の速い呼吸×3ラウンドまで（ラウンド間は休息をとる）', '17-4') ON CONFLICT (passage_id) DO NOTHING;
INSERT INTO breath_manager_v5.bm5_passages (passage_id, source_id, chapter, section_label, content, page_label) VALUES ('P23', 'BM-CH17', NULL, '17-4 安全に行うための基本 第5部共通ルール', '苦しくなるまで行わない。めまいが出たらやめる。息止めを無理に入れない。強い呼吸を長く続けない。食後すぐに強い呼吸をしない。疲労・病気・急性ストレス時に無理に実践しない。', '17-4') ON CONFLICT (passage_id) DO NOTHING;
INSERT INTO breath_manager_v5.bm5_passages (passage_id, source_id, chapter, section_label, content, page_label) VALUES ('P24', 'BM-CH17', NULL, '17-5 整理表の区分と教材での扱い', '自然呼吸観察：ヨガ呼吸の基礎／実践', '17-5') ON CONFLICT (passage_id) DO NOTHING;
INSERT INTO breath_manager_v5.bm5_passages (passage_id, source_id, chapter, section_label, content, page_label) VALUES ('P25', 'BM-CH17', NULL, '17-5 現代呼吸法と他章接続の要約', 'ボックス呼吸：吸う・止める・吐く・止めるを同じ長さで行う。息止めが苦しい人は無理に行わない。', '17-5') ON CONFLICT (passage_id) DO NOTHING;
INSERT INTO breath_manager_v5.bm5_passages (passage_id, source_id, chapter, section_label, content, page_label) VALUES ('P26', 'BM-CH17', NULL, '17-5 実践上の注意と選び方', 'ボックス呼吸や4-7-8呼吸には、息を止める要素が入ることがあります。苦しい人は無理に行わないでください。', '17-5') ON CONFLICT (passage_id) DO NOTHING;
INSERT INTO breath_manager_v5.bm5_passages (passage_id, source_id, chapter, section_label, content, page_label) VALUES ('P27', 'BM-CH17', NULL, '第5部総合ワーク 項目', '今の自分の状態：緊張している／疲れている／呼吸が浅い／集中しにくい／眠りが浅い／身体が重い／頭が忙しい／リラックスしたい／呼吸を観察したい／ヨガ前に整えたい', '第5部') ON CONFLICT (passage_id) DO NOTHING;
INSERT INTO breath_manager_v5.bm5_passages (passage_id, source_id, chapter, section_label, content, page_label) VALUES ('P28', 'BM-CH17', NULL, '第5部最終確認テスト 問題と正答', '1 CYPにおけるヨガの説明として最も近いものはどれですか。 正解：B', '第5部') ON CONFLICT (passage_id) DO NOTHING;
INSERT INTO breath_manager_v5.bm5_passages (passage_id, source_id, chapter, section_label, content, page_label) VALUES ('P29', 'BM-CH17', NULL, '第5部の完成形 第17章と注意書き', 'CYPに基づき、呼吸法を安全に、段階的に学ぶ', '第5部') ON CONFLICT (passage_id) DO NOTHING;
