INSERT INTO breath_manager_v5.bm5_retrieval_preview (retrieval_id, entry_type, entry_id, title, category_id, answer_preview, source_passage_ids, answer_constraints, safety_ids, related_entry_ids, production_ready, preview_allowed) VALUES ('RP066', 'knowledge', 'K066', '二酸化炭素が体外へ出るまで', 'physiology', '細胞で生じた二酸化炭素は血液で心臓・肺へ運ばれ、肺胞から呼気として体外へ出ます。
酸素を届ける流れと、二酸化炭素を戻す流れを対にして学びます。血中の運搬形態や割合はこの図から補いません。', ARRAY['P166']::text[], '[]'::jsonb, '{}', ARRAY['二酸化炭素が体外へ出るまで','CO₂','二酸化炭素','静脈','呼気','二酸化炭素が体外へ出るまでとは？']::text[], false, true) ON CONFLICT (retrieval_id) DO NOTHING;
INSERT INTO breath_manager_v5.bm5_retrieval_preview (retrieval_id, entry_type, entry_id, title, category_id, answer_preview, source_passage_ids, answer_constraints, safety_ids, related_entry_ids, production_ready, preview_allowed) VALUES ('RP067', 'knowledge', 'K067', '赤血球とヘモグロビンを区別する', 'physiology', 'ヘモグロビンは赤血球の中にある、酸素を運ぶたんぱく質です。
教材のタクシーはヘモグロビンを説明する比喩です。「満員になってから出発」「全て空席になる」を実際の循環の条件として説明しません。', ARRAY['P162','P163']::text[], '[{"issue_id":"I036","rule":"酸素タクシーは、結合部位を学ぶためのたとえです。必ず満席で出発し、全部を降ろすという意味ではありません。"}]'::jsonb, '{}', ARRAY['赤血球とヘモグロビンを区別する','赤血球','ヘモグロビン','Hb','赤血球とヘモグロビンを区別するとは？']::text[], false, true) ON CONFLICT (retrieval_id) DO NOTHING;
INSERT INTO breath_manager_v5.bm5_retrieval_preview (retrieval_id, entry_type, entry_id, title, category_id, answer_preview, source_passage_ids, answer_constraints, safety_ids, related_entry_ids, production_ready, preview_allowed) VALUES ('RP068', 'knowledge', 'K068', '細胞の構造を工場にたとえる', 'cell_energy', '教材は細胞膜を工場の壁、核を設計情報、ミトコンドリアをエネルギー利用に関わる場所として紹介しています。
リボソーム、小胞体、ゴルジ体も役割別に示されています。代表的な細胞の模式図であり、すべての細胞が同じ構成という意味ではありません。', ARRAY['P167']::text[], '[]'::jsonb, '{}', ARRAY['細胞の構造を工場にたとえる','細胞膜','核','リボソーム','小胞体','ゴルジ体','細胞の構造を工場にたとえるとは？']::text[], false, true) ON CONFLICT (retrieval_id) DO NOTHING;
INSERT INTO breath_manager_v5.bm5_retrieval_preview (retrieval_id, entry_type, entry_id, title, category_id, answer_preview, source_passage_ids, answer_constraints, safety_ids, related_entry_ids, production_ready, preview_allowed) VALUES ('RP069', 'knowledge', 'K069', '細胞呼吸と火のたとえ', 'cell_energy', '教材の「燃焼ではない」は、体内に炎が燃えているわけではないという説明として読みます。
栄養と酸素を利用する細胞内の過程を学ぶ比喩です。火との比較図を、そのまま厳密な化学反応式や熱が出ないという説明にしません。', ARRAY['P169']::text[], '[]'::jsonb, '{}', ARRAY['細胞呼吸と火のたとえ','細胞呼吸','燃焼','比喩','細胞呼吸と火のたとえとは？']::text[], false, true) ON CONFLICT (retrieval_id) DO NOTHING;
INSERT INTO breath_manager_v5.bm5_retrieval_preview (retrieval_id, entry_type, entry_id, title, category_id, answer_preview, source_passage_ids, answer_constraints, safety_ids, related_entry_ids, production_ready, preview_allowed) VALUES ('RP070', 'knowledge', 'K070', '疲労や眠気と教材の説明の範囲', 'safety', '教材には疲労や眠気と酸素・ATP・睡眠の関係が示されていますが、症状だけで原因を決める項目ではありません。
AI先生は「疲れるのはATP不足」「眠いのは低酸素」と断定せず、教材の一般説明と本人の状態の判断を分けます。', ARRAY['P159','P172','P211']::text[], '[{"issue_id":"I040","rule":"この図だけで、本人の疲労や眠気の原因をATP不足・低酸素と判断することはできません。"}]'::jsonb, ARRAY['S004']::text[], ARRAY['疲労や眠気と教材の説明の範囲','疲労','眠気','酸素不足','ATP不足','疲労や眠気と教材の説明の範囲とは？']::text[], false, true) ON CONFLICT (retrieval_id) DO NOTHING;
INSERT INTO breath_manager_v5.bm5_retrieval_preview (retrieval_id, entry_type, entry_id, title, category_id, answer_preview, source_passage_ids, answer_constraints, safety_ids, related_entry_ids, production_ready, preview_allowed) VALUES ('RP071', 'knowledge', 'K071', '圧受容体反射の学習', 'physiology', '教材は血圧の変化に対する調整を、頸動脈洞・大動脈弓・延髄を含む図で紹介しています。
呼吸との関連を学ぶ項目です。図の呼吸回数や血圧の波形を本人の治療目標にしません。原稿は高血圧等を呼吸法だけで改善すると説明しない方針です。', ARRAY['P174']::text[], '[{"issue_id":"I043","rule":"引用欄に著者・資料名・発行年・個別URL・参照箇所を記載する。機関名だけの引用は根拠の確定に使わない。"}]'::jsonb, '{}', ARRAY['圧受容体反射の学習','圧受容体','圧受容体反射','血圧','圧受容体反射の学習とは？']::text[], false, true) ON CONFLICT (retrieval_id) DO NOTHING;
INSERT INTO breath_manager_v5.bm5_retrieval_preview (retrieval_id, entry_type, entry_id, title, category_id, answer_preview, source_passage_ids, answer_constraints, safety_ids, related_entry_ids, production_ready, preview_allowed) VALUES ('RP072', 'knowledge', 'K072', '呼吸を案内するときの言葉', 'safety', '教材では「苦しくない範囲」「頑張りすぎない」「吐く時間を少し長く」といった声かけを紹介しています。
「病気が治る」「我慢して続ける」「HRVが高いほど健康」という説明を避ける方針です。めまいなどの中止条件も一緒に伝えます。', ARRAY['P177']::text[], '[]'::jsonb, ARRAY['S004']::text[], ARRAY['呼吸を案内するときの言葉','声かけ','指導','安全','HRV','呼吸を案内するときの言葉とは？']::text[], false, true) ON CONFLICT (retrieval_id) DO NOTHING;
INSERT INTO breath_manager_v5.bm5_retrieval_preview (retrieval_id, entry_type, entry_id, title, category_id, answer_preview, source_passage_ids, answer_constraints, safety_ids, related_entry_ids, production_ready, preview_allowed) VALUES ('RP073', 'knowledge', 'K073', '恒常性（ホメオスタシス）', 'physiology', '教材は恒常性を、体内の環境を一定に保とうとする働きとして説明しています。
体温・血圧・pHなどが学習例です。呼吸法だけであらゆる値が正常になるという意味ではありません。', ARRAY['P178']::text[], '[]'::jsonb, '{}', ARRAY['恒常性（ホメオスタシス）','恒常性','ホメオスタシス','恒常性（ホメオスタシス）とは？']::text[], false, true) ON CONFLICT (retrieval_id) DO NOTHING;
INSERT INTO breath_manager_v5.bm5_retrieval_preview (retrieval_id, entry_type, entry_id, title, category_id, answer_preview, source_passage_ids, answer_constraints, safety_ids, related_entry_ids, production_ready, preview_allowed) VALUES ('RP074', 'knowledge', 'K074', '闘争・逃走反応と本番の緊張', 'mind', '教材では、危険やプレッシャーに対応する身体反応として心拍・呼吸・筋緊張などの変化を紹介しています。
本番の緊張を必ずゼロにするという目標ではなく、本人が動きやすい状態を考えるための説明です。反応だけで診断しません。', ARRAY['P182','P226']::text[], '[]'::jsonb, '{}', ARRAY['闘争・逃走反応と本番の緊張','闘争逃走反応','緊張','ストレス','手汗','闘争・逃走反応と本番の緊張とは？']::text[], false, true) ON CONFLICT (retrieval_id) DO NOTHING;
INSERT INTO breath_manager_v5.bm5_retrieval_preview (retrieval_id, entry_type, entry_id, title, category_id, answer_preview, source_passage_ids, answer_constraints, safety_ids, related_entry_ids, production_ready, preview_allowed) VALUES ('RP075', 'knowledge', 'K075', '呼吸性の心拍変動', 'observation', '教材は呼吸に伴う心拍数や拍動間隔の変化を紹介しています。
心拍数とR-R間隔は同じ量ではありません。原図の軸・単位・波形方向は監修待ちのため、その図を健康度の採点や効果の判定には使いません。', ARRAY['P185']::text[], '[{"issue_id":"I041","rule":"呼吸と自律神経の関係を学びます。吸気・呼気を全身の神経状態が完全に切り替わるスイッチとして説明しません。"},{"issue_id":"I042","rule":"「心拍数」と「R-R間隔」を別の量として表示する。軸名・単位・波形の向きを確認して図を差し替える。"}]'::jsonb, '{}', ARRAY['呼吸性の心拍変動','呼吸性心拍変動','RSA','R-R間隔','呼吸性の心拍変動とは？']::text[], false, true) ON CONFLICT (retrieval_id) DO NOTHING;
INSERT INTO breath_manager_v5.bm5_retrieval_preview (retrieval_id, entry_type, entry_id, title, category_id, answer_preview, source_passage_ids, answer_constraints, safety_ids, related_entry_ids, production_ready, preview_allowed) VALUES ('RP076', 'knowledge', 'K076', '扁桃体の教材上の説明', 'mind', '教材は扁桃体を恐怖や不安に関わる領域として紹介し、警報装置にたとえています。
この比喩だけですべての感情や症状を説明するものではありません。特定の呼吸で必ず扁桃体が鎮まるという保証には使いません。', ARRAY['P194']::text[], '[]'::jsonb, '{}', ARRAY['扁桃体の教材上の説明','扁桃体','不安','恐怖','扁桃体の教材上の説明とは？']::text[], false, true) ON CONFLICT (retrieval_id) DO NOTHING;
INSERT INTO breath_manager_v5.bm5_retrieval_preview (retrieval_id, entry_type, entry_id, title, category_id, answer_preview, source_passage_ids, answer_constraints, safety_ids, related_entry_ids, production_ready, preview_allowed) VALUES ('RP077', 'knowledge', 'K077', '前頭前野と準備した力', 'mind', '教材は前頭前野を思考・判断・計画・集中・感情調整に関わる領域として紹介しています。
原稿は呼吸だけで能力が急に上がるわけではないと述べ、知識・経験・技術・練習と組み合わせる位置付けにしています。', ARRAY['P195']::text[], '[]'::jsonb, '{}', ARRAY['前頭前野と準備した力','前頭前野','判断','集中','計画','前頭前野と準備した力とは？']::text[], false, true) ON CONFLICT (retrieval_id) DO NOTHING;
INSERT INTO breath_manager_v5.bm5_retrieval_preview (retrieval_id, entry_type, entry_id, title, category_id, answer_preview, source_passage_ids, answer_constraints, safety_ids, related_entry_ids, production_ready, preview_allowed) VALUES ('RP078', 'knowledge', 'K078', '呼吸を注意の戻り先にする', 'mind', '教材のアンカーは、注意を戻す目印という意味です。呼吸の感覚や数を目印にします。
雑念に気づいたら、責めずに呼吸へ戻る練習として整理しています。手順と時間は呼吸カウント集中法の出典別の変種に保存しています。', ARRAY['P197']::text[], '[{"issue_id":"I045","rule":"図の順序案：吸って1 → 吐いて1 → 吸って2 → 吐いて2。3人目のラベルを本文に合わせる。"}]'::jsonb, '{}', ARRAY['呼吸を注意の戻り先にする','アンカー','雑念','呼吸カウント','呼吸を注意の戻り先にするとは？']::text[], false, true) ON CONFLICT (retrieval_id) DO NOTHING;
INSERT INTO breath_manager_v5.bm5_retrieval_preview (retrieval_id, entry_type, entry_id, title, category_id, answer_preview, source_passage_ids, answer_constraints, safety_ids, related_entry_ids, production_ready, preview_allowed) VALUES ('RP079', 'knowledge', 'K079', 'NREM睡眠とREM睡眠', 'sleep', '睡眠の分類として、NREM睡眠とREM睡眠を学びます。
NREM睡眠はN1・N2・N3の3段階として整理します。原図の4段階表示は、保存済みのNHLBI資料との照合に基づく修正対象です。周期を固定した睡眠タイマーには使いません。', ARRAY['P206']::text[], '[{"issue_id":"I046","rule":"NREM睡眠をN1・N2・N3の3段階に整理する。図の配置と本文をまとめて更新する。"}]'::jsonb, '{}', ARRAY['NREM睡眠とREM睡眠','NREM','REM','ノンレム','レム','睡眠段階','NREM睡眠とREM睡眠とは？']::text[], false, true) ON CONFLICT (retrieval_id) DO NOTHING;
INSERT INTO breath_manager_v5.bm5_retrieval_preview (retrieval_id, entry_type, entry_id, title, category_id, answer_preview, source_passage_ids, answer_constraints, safety_ids, related_entry_ids, production_ready, preview_allowed) VALUES ('RP080', 'knowledge', 'K080', '睡眠中の呼吸の特徴', 'sleep', '教材では、眠っている間の呼吸は主に自動調整され、睡眠段階や筋肉の状態にも影響されると説明しています。
睡眠中は誰でも同じ深さ・同じ間隔で呼吸するという意味ではありません。いびきや呼吸停止の指摘は別に記録して扱います。', ARRAY['P207']::text[], '[{"issue_id":"I043","rule":"引用欄に著者・資料名・発行年・個別URL・参照箇所を記載する。機関名だけの引用は根拠の確定に使わない。"}]'::jsonb, '{}', ARRAY['睡眠中の呼吸の特徴','睡眠','自動調整','呼吸リズム','睡眠中の呼吸の特徴とは？']::text[], false, true) ON CONFLICT (retrieval_id) DO NOTHING;
INSERT INTO breath_manager_v5.bm5_retrieval_preview (retrieval_id, entry_type, entry_id, title, category_id, answer_preview, source_passage_ids, answer_constraints, safety_ids, related_entry_ids, production_ready, preview_allowed) VALUES ('RP081', 'knowledge', 'K081', 'いびきと睡眠時無呼吸を区別する', 'sleep', '教材は、いびきを空気の通り道が狭くなり、周囲の組織が振動して出る音として説明しています。
いびきだけで睡眠時無呼吸と診断しません。呼吸停止の指摘や強い日中の眠気などは相談につなぐ別項目と組み合わせます。', ARRAY['P210']::text[], '[]'::jsonb, '{}', ARRAY['いびきと睡眠時無呼吸を区別する','いびき','SAS','睡眠時無呼吸','いびきと睡眠時無呼吸を区別するとは？']::text[], false, true) ON CONFLICT (retrieval_id) DO NOTHING;
INSERT INTO breath_manager_v5.bm5_retrieval_preview (retrieval_id, entry_type, entry_id, title, category_id, answer_preview, source_passage_ids, answer_constraints, safety_ids, related_entry_ids, production_ready, preview_allowed) VALUES ('RP082', 'knowledge', 'K082', '鼻呼吸がしにくい場合の教材方針', 'safety', '教材は鼻づまりなどで鼻呼吸が難しい場合に、鼻呼吸だけを強制しないとしています。
自己判断で口閉じテープをすすめる手順は作りません。鼻の通りやいびきなどを確認し、必要な相談につなぐという原稿の方針を保存しています。', ARRAY['P208','P209','P196']::text[], '[{"issue_id":"I047","rule":"鼻の構造・NOの説明と、脳・免疫・いびき・睡眠への効果の主張を別に扱う。効能の矢印は根拠確認まで保留する。"}]'::jsonb, ARRAY['S004']::text[], ARRAY['鼻呼吸がしにくい場合の教材方針','鼻づまり','口呼吸','口閉じテープ','鼻呼吸がしにくい場合の教材方針とは？']::text[], false, true) ON CONFLICT (retrieval_id) DO NOTHING;
INSERT INTO breath_manager_v5.bm5_retrieval_preview (retrieval_id, entry_type, entry_id, title, category_id, answer_preview, source_passage_ids, answer_constraints, safety_ids, related_entry_ids, production_ready, preview_allowed) VALUES ('RP083', 'knowledge', 'K083', '眠りの準備と生活習慣', 'sleep', '教材は、呼吸法とともに寝起きの時刻、寝室、光、電子機器、食事などの生活を振り返ります。
呼吸法だけで睡眠を解決するという説明にはしません。記録を続け、気になる状態が続くときの相談とは分けて扱います。', ARRAY['P200','P212']::text[], '[]'::jsonb, '{}', ARRAY['眠りの準備と生活習慣','睡眠習慣','就寝準備','光','生活リズム','眠りの準備と生活習慣とは？']::text[], false, true) ON CONFLICT (retrieval_id) DO NOTHING;
INSERT INTO breath_manager_v5.bm5_retrieval_preview (retrieval_id, entry_type, entry_id, title, category_id, answer_preview, source_passage_ids, answer_constraints, safety_ids, related_entry_ids, production_ready, preview_allowed) VALUES ('RP084', 'knowledge', 'K084', '姿勢と呼吸を一緒に観察する', 'conditioning', '教材はデスクワークなどで肩や首に力が入りやすいとき、姿勢と胸郭の動きを一緒に観察する考え方を紹介しています。
肩こりや頭痛の原因を呼吸だけに決めません。姿勢リセット呼吸は、胸を無理に張らず伸ばすという原稿の注意とともに扱います。', ARRAY['P214']::text[], '[]'::jsonb, '{}', ARRAY['姿勢と呼吸を一緒に観察する','姿勢','肩こり','胸郭','デスクワーク','姿勢と呼吸を一緒に観察するとは？']::text[], false, true) ON CONFLICT (retrieval_id) DO NOTHING;
INSERT INTO breath_manager_v5.bm5_retrieval_preview (retrieval_id, entry_type, entry_id, title, category_id, answer_preview, source_passage_ids, answer_constraints, safety_ids, related_entry_ids, production_ready, preview_allowed) VALUES ('RP085', 'knowledge', 'K085', '季節と体調の記録', 'lifestyle', '教材は季節や天気、鼻呼吸のしやすさ、呼吸の深さ、体調を記録して振り返る方法を紹介しています。
春だから特定の呼吸法、冷えるから特定の体質、と自動判定する表にはしません。本人の観察と実施後の変化を記録します。', ARRAY['P219']::text[], '[]'::jsonb, '{}', ARRAY['季節と体調の記録','季節','天気','体調','記録','季節と体調の記録とは？']::text[], false, true) ON CONFLICT (retrieval_id) DO NOTHING;
INSERT INTO breath_manager_v5.bm5_retrieval_preview (retrieval_id, entry_type, entry_id, title, category_id, answer_preview, source_passage_ids, answer_constraints, safety_ids, related_entry_ids, production_ready, preview_allowed) VALUES ('RP086', 'knowledge', 'K086', '声を使う場面と呼吸の工夫', 'voice', '教材は、歌唱・スピーチ・プレゼン・アナウンス・マイク使用を分けて、息の流れや文の区切り、間、力みを学びます。
歌唱では息を強く押し出さず、スピーチでは文の区切り、プレゼンでは話し始める前の一呼吸が例示されています。制作上の監修候補は、監修済みを意味しません。', ARRAY['P224']::text[], '[{"issue_id":"I050","rule":"「監修候補・未依頼」という制作メモとして保存する。教材本文やAIの回答に監修済みと表示しない。"}]'::jsonb, '{}', ARRAY['声を使う場面と呼吸の工夫','歌唱','スピーチ','マイク','アナウンス','声を使う場面と呼吸の工夫とは？']::text[], false, true) ON CONFLICT (retrieval_id) DO NOTHING;
INSERT INTO breath_manager_v5.bm5_retrieval_preview (retrieval_id, entry_type, entry_id, title, category_id, answer_preview, source_passage_ids, answer_constraints, safety_ids, related_entry_ids, production_ready, preview_allowed) VALUES ('RP087', 'knowledge', 'K087', 'ヨガを日常の自己観察に使う', 'yoga_theory', '教材は、今の身体・呼吸・心に気づく習慣としてヨガを生活に取り入れる考え方を紹介しています。
完璧なポーズを目標にしすぎず、小さく始めて無理なく続けるという位置付けです。原稿は医療の代替ではないと明記しています。', ARRAY['P230']::text[], '[]'::jsonb, '{}', ARRAY['ヨガを日常の自己観察に使う','ヨガ','ウェルネス','自己観察','ヨガを日常の自己観察に使うとは？']::text[], false, true) ON CONFLICT (retrieval_id) DO NOTHING;
INSERT INTO breath_manager_v5.bm5_retrieval_preview (retrieval_id, entry_type, entry_id, title, category_id, answer_preview, source_passage_ids, answer_constraints, safety_ids, related_entry_ids, production_ready, preview_allowed) VALUES ('RP088', 'catalog', 'C001', '自然呼吸観察', 'practice', '自然呼吸観察は、教材では「呼吸に気づく」を目的に紹介されています。
1. 楽な姿勢で座り、背すじを軽く伸ばす。
2. 肩、あご、お腹の力を抜く。
3. 鼻から自然に吸い、鼻から自然に吐く。
4. 呼吸を変えようとせず、流れを観察する。
5. 目安は1〜3分です。
原稿の目安：1〜3分
苦しさやめまいが出たら中止し、不調を押して続けません。
注意：呼吸を深く・遅くしようと操作しない。 鼻から自然に呼吸できない場合の代替手順は本原稿に未記載。', ARRAY['P13','P14','P23','P115']::text[], '[{"issue_id":"I010","rule":"この教材では、初心者はカパラバティの特徴と注意点を学びます。実践の回数は案内しません。"},{"issue_id":"I011","rule":"該当する注意は「本教材の方針」として記載し、CYPのカパラバティ節にあると断定しない。"}]'::jsonb, ARRAY['S001','S004']::text[], ARRAY['自然呼吸観察','自然な呼吸の観察','観察','初心者','自然呼吸観察とは？','自然呼吸観察の注意点は？']::text[], false, true) ON CONFLICT (retrieval_id) DO NOTHING;
INSERT INTO breath_manager_v5.bm5_retrieval_preview (retrieval_id, entry_type, entry_id, title, category_id, answer_preview, source_passage_ids, answer_constraints, safety_ids, related_entry_ids, production_ready, preview_allowed) VALUES ('RP089', 'catalog', 'C002', 'ナディショーダナ簡易版', 'practice', 'ナディショーダナ簡易版は、教材では「左右の鼻を交互に使い、ゆっくり整える」を目的に紹介されています。
1. 楽な姿勢で座り、背すじと頭をまっすぐにする。
2. 右手を鼻の前へ。親指で右鼻を軽く閉じ、左鼻から吸う。
3. 薬指・小指で左鼻を軽く閉じ、同時に親指をゆるめ、右鼻から吐く。
4. そのまま右鼻から吸う。
5. 親指で右鼻を軽く閉じ、同時に薬指・小指をゆるめ、左鼻から吐く。
6. ここまでを1往復とし、原稿では3〜5往復。息止めを入れない。
原稿の目安：3〜5往復。最初は吸う・吐くを同じ長さ。
苦しさやめまいが出たら中止し、不調を押して続けません。
原稿で行わないとされる条件：強い鼻づまり
注意：鼻を強く押さえない。 自分のペースで行う。', ARRAY['P16','P17','P23']::text[], '[{"issue_id":"I008","rule":"引用するCYPの版・発行年・ページを明記する。シータリーの掲載を確認できるまでは「このCYPに明記」と書かない。"},{"issue_id":"I009","rule":"簡易版の本文に合わせ、耳を塞ぐ動作は手順に追加しない。イラストも本文と一致させる。"},{"issue_id":"I010","rule":"この教材では、初心者はカパラバティの特徴と注意点を学びます。実践の回数は案内しません。"},{"issue_id":"I011","rule":"該当する注意は「本教材の方針」として記載し、CYPのカパラバティ節にあると断定しない。"}]'::jsonb, ARRAY['S001','S004']::text[], ARRAY['ナディショーダナ簡易版','ナディショーダナ','ナディショーダナ／アヌローマ・ヴィローマ','アヌローマ・ヴィローマ','左右交互鼻呼吸','落ち着き','左右交互','初心者','ナディショーダナ簡易版とは？','ナディショーダナ簡易版の注意点は？']::text[], false, true) ON CONFLICT (retrieval_id) DO NOTHING;
INSERT INTO breath_manager_v5.bm5_retrieval_preview (retrieval_id, entry_type, entry_id, title, category_id, answer_preview, source_passage_ids, answer_constraints, safety_ids, related_entry_ids, production_ready, preview_allowed) VALUES ('RP090', 'catalog', 'C003', 'ブラーマリー簡易版', 'practice', 'ブラーマリー簡易版は、教材では「音と響きに注意を向ける」を目的に紹介されています。
1. 楽な姿勢で座り、目を閉じる。
2. 鼻から静かに吸う。
3. 吐くときに小さく「んー」と響かせる。
4. 頭や顔に響く感覚を観察する。
5. 原稿の目安は3〜5回。音を強く出さず、心地よい範囲で行う。
原稿の目安：3〜5回
苦しさやめまいが出たら中止し、不調を押して続けません。
原稿で行わないとされる条件：鼻や耳の感染症、鼻や耳の痛み、鼻や耳の強い違和感
注意：耳を塞ぐ動作は本文手順にないため追加しない。', ARRAY['P20','P23']::text[], '[{"issue_id":"I009","rule":"簡易版の本文に合わせ、耳を塞ぐ動作は手順に追加しない。イラストも本文と一致させる。"},{"issue_id":"I008","rule":"引用するCYPの版・発行年・ページを明記する。シータリーの掲載を確認できるまでは「このCYPに明記」と書かない。"},{"issue_id":"I010","rule":"この教材では、初心者はカパラバティの特徴と注意点を学びます。実践の回数は案内しません。"},{"issue_id":"I011","rule":"該当する注意は「本教材の方針」として記載し、CYPのカパラバティ節にあると断定しない。"}]'::jsonb, ARRAY['S001','S004']::text[], ARRAY['ブラーマリー簡易版','ブラーマリー','ハミング呼吸','集中の準備','ハミング','初心者','ブラーマリー簡易版とは？','ブラーマリー簡易版の注意点は？']::text[], false, true) ON CONFLICT (retrieval_id) DO NOTHING;